name: newBranch
on: 
    repository_dispatch:
        types: generateBranch
jobs:
  generateAppBranch:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: https://clkasgpccskyojaxpytr.supabase.co
      SUPABASE_SERVICE_ROLE: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsa2FzZ3BjY3NreW9qYXhweXRyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5MDI3MTY3MiwiZXhwIjoyMDA1ODQ3NjcyfQ.uYYeeysnIf46gv1qAY-Kf0tclBcmQqc5n-viBfG9I28
      SUPABASE_ACCESS_TOKEN: sbp_cd5d3b1f1d6a9ed1306092cbfedd641e6dcfd2f7
      SUPABASE_DB_PASSWORD: ste15STy15121981#
      PROJECT_ID: clkasgpccskyojaxpytr
    permissions:
      contents: write
    steps:
      - name: checkoutCode
        uses: actions/checkout@v4
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
      - name: supabase install
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: init project
        run: supabase init
      - name: link project 
        run: supabase link --project-ref ${{ env.PROJECT_ID }}
      - name: download app
        run: supabase storage cp -r --experimental ss:///appBuilderOutput . 
      - name: create right folder structure via cp
        run: cp -r -f ./appBuilderOutput/* .
      - name: remove appBuilderOutput folder
        run: rm -R ./appBuilderOutput
      - name: remove supabase
        run: rm -R ./supabase
      - name: stage changed files
        run: git add .
      - name: push in a new branch
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:    
        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default: github_actor
          default_author: github_actions
    
        # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
        # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ. 
        # Default: --tags --force
          fetch: false
    
        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'appCreator initial'
    
        # If this input is set, the action will push the commit to a new branch with this name.
        # Default: ''
          new_branch: '${{ github.event.client_payload.branchName }}-${{ env.NOW }}'
    
        # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
        # - ignore -> errors will be logged but the step won't fail
        # - exitImmediately -> the action will stop right away, and the step will fail
        # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
        # Default: ignore
          pathspec_error_handling: ignore
    
        # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
        # Default: true
          push: true
      
      
       